name: cmake build win

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: curl
      run: which curl

    - name: install vcpkg
      run: |
        dir -s "C:\Program Files (x86)\Microsoft Visual Studio"
        dir -s "C:\Program Files\Microsoft Visual Studio"
        cd ${{github.workspace}}
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg install qtbase
        cd ${{github.workspace}}
    - name: install cmake
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x64"
        $build_dir="build"
        cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -B $build_dir
        cmake --build $build_dir
        dir
        cd $build_dir
    - name: run shell
      run: |
        git clone https://android.googlesource.com/platform/manifest.git
        cd manifest
        git tag
        git checkout android-4.4.2_r1
        python windows/download_src.py